//SDL
#define WINDOW_TITLE "2D"
#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 780

//world
#define CELL_NUMBER 25
#define FOOD_NUMBER 100

//cell
#define CELL_SIZE 10
#define CELL_SIZE_ENERGY_COST 0.6
#define CELL_SPEED 50
#define CELL_SPEED_ENERGY_COST 0.1
#define CELL_FRICTION 0.9
#define CHILDBIRTH_ENERGY 40
#define BIRTH_ENERGY 20
#define MUTATION_CHANCE 20

//food
#define FOOD_SIZE 5
#define FOOD_ENERGY 25
#define FOOD_SPAWN_RATE 100

//brain
#define BRAIN_MUTATION_CHANCE 10