//SDL
#define WINDOW_TITLE "2D"
#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 780

//world
#define CELL_NUMBER 25
#define FOOD_NUMBER 100

//cell
#define CELL_SIZE 10
#define CELL_SIZE_ENERGY_COST 0.6
#define CELL_SIZE_MUTATION_CHANCE 10
#define CELL_SPEED 50
#define CELL_SPEED_ENERGY_COST 0.1
#define CELL_SPEED_MUTATION_CHANCE 10
#define CELL_COLOR_MUTATION_CHANCE 10
#define CELL_FRICTION 0.95
#define CHILDBIRTH_ENERGY 40
#define BIRTH_ENERGY 20

//food
#define FOOD_SIZE 5
#define FOOD_ENERGY 25
#define FOOD_SPAWN_RATE 100

//brain
#define BRAIN_MUTATION_CHANCE 10
#define BRAIN_INPUTS 4
#define BRAIN_HIDDEN_LAYERS 2
#define BRAIN_HIDDEN_LAYER_SIZE 4
#define BRAIN_OUTPUTS 2